org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.enableBuildConfigAsBytecode=true
org.gradle.configuration-cache=true
# 版本名 后缀加Dev代表内部开发版，例如"4.20 Dev"
VERSION_NAME=4.20.6.1 Dev
# 版本号
VERSION_CODE=268
# 可选启用：Debug版本包名与Release不同
USE_DEBUG_PACKAGE_SUFFIX=false
# 可选启用：仅构建arm64-v8a架构的Debug版本，适用于调试阶段加快构建速度
ONLY_ARM64_DEBUG=false
# SharedNav是否使用本地AAR
USE_LOCAL_SHAREDNAV=false